# HTTP API setting
[http]
bind = "127.0.0.1"
port = 8080
ws_port = 9090
# Place with html files
webroot = "./assets"

# Traktor setup settings for now playing decision logic
[mixing]
# List of decks
deck_list = [ "A", "B", "C", "D" ]
# Deck assignments to channels
deck_channel_map = { A = 1, B = 2, C = 3, D = 4 }
